### ISSUE TITLE
Fails to push changes

### ISSUE THREAD

**Issue by anders-wind** [dineshsonachalam/markdown-autodocs#21]
Hi, 

Thanks for the tool. Im trying to set it up for our repo but im having difficulties getting it to push the changes to my branch.

Heres the output:
```
[2022-08-26T08:45:32.099] [INFO] default - Auto documented code-block in ./README.md
✔ README.md Updated
 Transforms run
  ⁕ CODE:src=./examples/unit_example.cpp 

[feature/inject_examples_into_readme 3a92010] Update README.md
 1 file changed, 83 insertions(+)
error: src refspec merge does not match any
error: failed to push some refs to 'https://github.com/twig-energy/stronk'
ma_cli_command: markdown-autodocs --outputFilePath ./README.md --category code-block --repo twig-energy/stronk --branch merge --accessToken ***
```
Here's my workflow file:

```
name: Embed examples into README

on:
  pull_request:
    branches:
      - main

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.5
        with:
          commit_message: Update README.md
          output_file_paths: '[./README.md]'
          categories: '[code-block]'

```
This is the PR im trying to add it in: https://github.com/twig-energy/stronk/pull/11 

I will probably rebase and edit the commits in the PR while trying different solutions.

**Comment by dineshsonachalam** [comment]
Hi @anders-wind,

Thanks for reaching out. I made a mistake in the branch parsing logic in the Markdown Autodocs library which caused this pipeline failure. This issue has been resolved now. Please restart the pipeline for your dev branch and you're good to go.

Markdown Autodocs autogenerated code block on your dev branch - **inject_examples_into_readme**

<img width="451" alt="image" src="https://user-images.githubusercontent.com/12673979/187045327-2c899be0-fe83-47f0-8701-9368fc5cb3e9.png">

**Reference:**  https://github.com/dineshsonachalam/stronk/tree/feature/inject_examples_into_readme

Please feel free to reach out to me if you have any questions.

**Comment by anders-wind** [comment]
Wow thanks for fixing so quickly! I think however you need to make a new release for me to try it out :)

**Comment by dineshsonachalam** [comment]
@anders-wind, 

I create a new release(v1.0.6). You can use the below GitHub Action configuration.

```
name: Embed examples into README

on:
  push:
    branches:    
      - '**'  # matches every branch

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.6 
        with:
          commit_message: Update README.md
          output_file_paths: '[./README.md]'
          categories: '[code-block]'
```

**Reference:** https://github.com/dineshsonachalam/stronk/blob/feature/inject_examples_into_readme/.github/workflows/update_readme.yml

Markdown Autodocs autogenerated code block on your dev branch - **inject_examples_into_readme**

**Reference:** https://github.com/dineshsonachalam/stronk/tree/feature/inject_examples_into_readme#examples

Please let me know if you have any questions.

**Comment by anders-wind** [comment]
Hmmm, still getting errors if I'm doing it as a PR.
```
on:
  pull_request:
    branches:
    - main
```

Is it possible to support this? I do not allow direct commits on my main branch and I dont want to enforce a naming scheme for branches

**Comment by anders-wind** [comment]
Seems like one can use: `github.ref_name` frrom the github contexts to get the branch name: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context. I see that you currently use `${{ github.ref }}`

**Comment by dineshsonachalam** [comment]
The issue has been resolved. We need to use ${{ github.head_ref }} to get the branch name. 

**Reference:** https://github.com/dineshsonachalam/stronk/pull/1/commits/58e91583ec7fb1ee9de4d92ce24a32738e3cef8f
cc: @anders-wind

**Comment by anders-wind** [comment]
Thanks a lot for fixing 👍
